### ISSUE TITLE
requests?

### ISSUE THREAD

**Issue by st0le** [Rauwomos/CSGOMusicPlayer#1]
I don't think you need requests. Your readme should mention flask instead.

**Comment by Davy1992** [comment]
Why did you enable reporting of all the data when you are only using **player_id** and **player_state**.
Why are you asking the server for **player_weapons** for example and you never do anything with it. 
This only creates overhead.

**Comment by rowan-walshe** [comment]
Thanks for pointing that out. I was just using the example cfg file from the valve developer wiki. I've removed the requests for unused data.
