### ISSUE TITLE
python setup.py egg_info failed with error code 1

### ISSUE THREAD

**Issue by ghost** [Rauwomos/CSGOMusicPlayer#4]
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Nathan\AppData\Local\Temp\pip-build-j1zksdo6\pyscreeze\

I have tried to upgrade setup tools and everything the first page of google results gives me.

**Comment by Jackevansevo** [comment]
If there's a log/stack trace please post the output, so we can figure out what's going on

After installing setuptoosl with

`$ sudo python ez_setup.py` 

Ensure you run

`$ sudo easy_install pip`

**Comment by ghost** [comment]
I installed setuptools again.  Here is the current output.
C:\Users\Nathan>cd Downloads

C:\Users\Nathan\Downloads>cd CSGOMusicPlayer

C:\Users\Nathan\Downloads\CSGOMusicPlayer>pip install -r requirements-windows.txt
Collecting Pillow==3.1.0 (from -r requirements-windows.txt (line 1))
  Using cached Pillow-3.1.0.tar.gz
Collecting Flask==0.10.1 (from -r requirements-windows.txt (line 2))
  Using cached Flask-0.10.1.tar.gz
Collecting PyAutoGUI==0.9.33 (from -r requirements-windows.txt (line 3))
  Using cached PyAutoGUI-0.9.33.zip
Collecting Werkzeug>=0.7 (from Flask==0.10.1->-r requirements-windows.txt (line 2))
  Using cached Werkzeug-0.11.11-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from Flask==0.10.1->-r requirements-windows.txt (line 2))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from Flask==0.10.1->-r requirements-windows.txt (line 2))
  Using cached itsdangerous-0.24.tar.gz
Collecting pymsgbox (from PyAutoGUI==0.9.33->-r requirements-windows.txt (line 3))
  Using cached PyMsgBox-1.0.3.zip
Collecting PyTweening>=1.0.1 (from PyAutoGUI==0.9.33->-r requirements-windows.txt (line 3))
  Using cached PyTweening-1.0.3.zip
Collecting pyscreeze (from PyAutoGUI==0.9.33->-r requirements-windows.txt (line 3))
  Using cached PyScreeze-0.1.8.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nathan\AppData\Local\Temp\pip-build-m7fzkws7\pyscreeze\setup.py", line 6, in <module>
        version=**import**('pyscreeze').**version**,
      File "C:\Users\Nathan\AppData\Local\Temp\pip-build-m7fzkws7\pyscreeze\pyscreeze__init__.py", line 21, in <module>
        from PIL import Image
    ImportError: No module named 'PIL'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Nathan\AppData\Local\Temp\pip-build-m7fzkws7\pyscreeze\

**Comment by Jackevansevo** [comment]
Are you on Python3 or Python2?

have you tried `pip install Pillow`?

**Comment by ghost** [comment]
I have both Python2.7 and 3.4 and both are in my path in my environment variables.
pip install Pillow spits out an error.
C:\Users\Nathan>pip install Pillow
Collecting Pillow
  Downloading Pillow-3.3.1.zip (10.8MB)
    100% |################################| 10.8MB 83kB/s
Installing collected packages: Pillow
  Running setup.py install for Pillow ... error
    Complete output from command c:\python34\python.exe -u -c "import setuptools, tokenize;**file**='C:\Users\Nathan\AppData\Local\Temp\pip-build-9dw399cr\Pillow\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\Nathan\AppData\Local\Temp\pip-tb1st7t1-record\install-record.txt --single-version-externally-managed --compile:
    Single threaded build for windows
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\PIL
    copying PIL\BdfFontFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ContainerIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ExifTags.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\features.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FontFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GdImageFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\Image.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageChops.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageCms.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageColor.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageDraw.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageDraw2.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageEnhance.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFilter.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFont.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageGrab.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageMath.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageMode.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageMorph.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageOps.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImagePalette.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImagePath.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageQt.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageSequence.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageShow.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageStat.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageTk.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageTransform.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageWin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\JpegPresets.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\OleFileIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PaletteFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PcfFontFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PSDraw.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PyAccess.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TarIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TiffTags.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\WalImageFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL_binary.py -> build\lib.win-amd64-3.6\PIL
    copying PIL_tkinter_finder.py -> build\lib.win-amd64-3.6\PIL
    copying PIL_util.py -> build\lib.win-amd64-3.6\PIL
    copying PIL__init__.py -> build\lib.win-amd64-3.6\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    writing top-level names to Pillow.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

```
reading manifest file 'Pillow.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.sh'
no previously-included directories found matching 'docs\_static'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.landscape.yaml'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'build_children.sh'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'Pillow.egg-info\SOURCES.txt'
copying PIL\OleFileIO-README.md -> build\lib.win-amd64-3.6\PIL
running build_ext
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Nathan\AppData\Local\Temp\pip-build-9dw399cr\Pillow\setup.py", line 753, in <module>
    zip_safe=not debug_build(), )
  File "c:\python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\python34\lib\site-packages\setuptools\command\install.py", line 61, in run
    return orig.install.run(self)
  File "c:\python34\lib\distutils\command\install.py", line 539, in run
    self.run_command('build')
  File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\python34\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "c:\python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\python34\lib\distutils\command\build_ext.py", line 338, in run
    self.build_extensions()
  File "C:\Users\Nathan\AppData\Local\Temp\pip-build-9dw399cr\Pillow\setup.py", line 521, in build_extensions
    ' using --disable-%s, aborting' % (f, f))
ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

----------------------------------------
```

Command "c:\python34\python.exe -u -c "import setuptools, tokenize;**file**='C:\Users\Nathan\AppData\Local\Temp\pip-build-9dw399cr\Pillow\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" in

**Comment by Jackevansevo** [comment]
Try upgrading pip 

`pip install --upgrade pip`

**Comment by ghost** [comment]
Pip already up to date.
C:\Users\Nathan>pip install --upgrade pip
Requirement already up-to-date: pip in c:\python34\lib\site-packages

**Comment by Jackevansevo** [comment]
If you haven't already just try and install all the dependencies with easy_install. And / or try setting up a virtual environemnt and install the deps inside that.

Python on Windows is a complete can of worms, so I suggest if you have any more issues you ask on the #python irc channel on freenode: http://irc.lc/freenode/python People there might be able to help you

**Comment by ghost** [comment]
I have already done that.  Thanks anyway.

**Comment by rowan-walshe** [comment]
I'm currently don't have access to anything to test it on. I'll be able to have a look at it this weekend.

**Comment by ghost** [comment]
I figured it out.  I need to install "Image" by running "pip install Image"

**Comment by Jackevansevo** [comment]
Glad you figured it out 
![](https://media.giphy.com/media/zac5EvG19YCVa/giphy.gif)
